name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ # repo root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: |
          echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env
          echo "BASE_PATH=/${{ github.repository }}" >> $GITHUB_ENV
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
